apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
data:
  APP_NAME: fraud-detection-api
  APP_ENV: production
  LOG_LEVEL: INFO
  MODEL_PATH: /app/models/fraud_model.joblib
  MODEL_METADATA_PATH: /app/models/model_metadata.json
  MLFLOW_TRACKING_URI: http://mlflow:5000
  MLFLOW_EXPERIMENT_NAME: fraud-detection
  FRAUD_THRESHOLD: "0.50"
